apiVersion: cloud.redhat.com/v1alpha1
kind: Frontend
metadata:
  name: chrome
spec:
  # Add fields here
  envName: chrome
  title: Chrome
  deploymentRepo: http://test
  API:
    versions:
    - v1
  frontend:
    paths:
    - /apps/chrome
  image: quay.io/redhat-cloud-services/chrome-frontend
