apiVersion: cloud.redhat.com/v1alpha1
kind: Frontend
metadata:
  name: inventory
spec:
  # Add fields here
  envName: fon
  title: Inventory
  deploymentRepo: http://test
  API:
    versions:
    - v1
  frontend:
    paths:
    - /insights/inventory
  image: quay.io/redhat-cloud-services/inventory-frontend
  navItem:
    appId: "inventory"
    title: "Inventory"
    href: "/insights/inventory"
    product: "Red Hat Insights"