apiVersion: cloud.redhat.com/v1alpha1
kind: Frontend
metadata:
  name: inventory
spec:
  # Add fields here
  envName: boot
  title: Inventory
  deploymentRepo: http://test
  API:
    versions:
    - v1
  frontend:
    paths:
    - test
  image: quay.io/redhat-cloud-services/inventory-frontend