apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
kindContainers:
- controller
crdDir: config/crd/test-resources/
testDirs:
- tests/e2e/
timeout: 320
parallel: 1
commands:
- command: make kuttl-release
- command: oc apply -f manifest.yaml
