# permissions for end users to edit frontends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frontendenvironment-editor-role
  labels: 
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - cloud.redhat.com
  resources:
  - frontendenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - frontendenvironments/status
  verbs:
  - get
