apiVersion: cloud.redhat.com/v1alpha1
kind: FrontendEnvironment
metadata:
  name: env-boot
spec:
  sso: https://env-boot-auth/auth/
  targetNamespaces:
    - feo-testing
  monitoring:
    mode: "local"
    disabled: false
  serviceCategories:
    - id: automation
      title: Automation
      groups:
        - id: ansible
          title: Ansible
        - id: rhel
          title: Red Hat Enterprise Linux
    - id: iam
      title: Identity and Access Management
      groups:
        - id: iam
          title: IAM
