apiVersion: cloud.redhat.com/v1alpha1
kind: Frontend
metadata:
  name: landing
spec:
  # Add fields here
  envName: env-boot
  title: landing
  deploymentRepo: http://test
  API:
    versions:
    - v1
  frontend:
    paths:
    - /apps/landing
  image: quay.io/redhat-cloud-services/landing
  module:
    manifestLocation: "/apps/landing/fed-mods.json"
    modules:
    - id: "landing"
      module: "./RootApp"
      routes:
      - pathname: /
        exact: true
  searchEntries:
    - id: "landing"
      title: "Landing"
      href: /
      description: "Landing page description"
      alt_title:
        - HCC Home page
        - Home
    - id: "landing-widgets"
      title: "Widget fantastic"
      href: /widgets
      description: "Widget"
  widgetRegistry:
    - scope: "landing"
      module: "./RandomWidget"
      config:
        icon: "CogIcon"
        title: "Random Widget"
      defaults:
        sm: 
          w: 1
          h: 1
          maxH: 1
          minH: 1
        md: 
          w: 1
          h: 1
          maxH: 1
          minH: 1
        lg: 
          w: 1
          h: 1
          maxH: 1
          minH: 1
        xl: 
          w: 1
          h: 1
          maxH: 1
          minH: 1
  serviceTiles:
    - section: automation
      group: ansible
      id: ansible-link
      title: Ansible FOO
      href: /ansible/foo
      description: Ansible FOO description thing
      icon: AnsibleIcon
    - section: iam
      group: iam
      id: iam-link
      title: IAM FOO
      href: /iam
      description: Some Iam thing
      icon: IAMIcon
      isExternal: false
  navigationSegments:
    - segmentId: inventory-partial
      bundleId: insights
      position: 100
      navItems:
        - id: landing
          title: Landing section
          href: /apps/landing
        - id: bar
          title: Some new link
          expandable: true
          routes:
            - id: foo
              title: Foo
              href: /nested/bar
        - id: baz
          title: Some new link
          href: /baz
