---
name: Run Unit Tests

'on':
  - pull_request

jobs:

  testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v5
        name: Set up golang 1.22
        with:
          go-version: '1.22.7'
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Install package and dependencies
        run: |
          make
      - name: Run Tests
        run: make test
